name: Sedstart local

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: macos-15
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runlocal@main
        with:
          api_key: ${{ secrets.SEDSTART_KEY }}
          project_id: 418
          suite_id: 391
          profile_id: 848
          browser: 'msedge'
          headless: false
          environment: QA
