name: TC05 - Project 418 with test 2170

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.API_KEY_A }}
          project_id: 418
          test_id: 2170
          profile_id: 848
          browser: chrome
          headless: false
          environment: "QA"
