name: TC08 - Project 398 wrong profile

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.API_KEY_B }}
          project_id: 398
          test_id: 2170
          profile_id: 848
          browser: chrome
          headless: false
          environment: "QA"
