name: TC06 - Project 398 with test 1974

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.API_KEY_B }}
          project_id: 398
          test_id: 1974
          profile_id: 900
          browser: chrome
          headless: false
          environment: "QA"
